import { GROUND_CONTROL_DIR, normalize } from '@ground-control/core';

/**
 * Bumped when a field's meaning changes, not when one is added: two extension versions share one home, and an added
 * field is absent to the older reader and defaulted by the newer one. A marker of another version is replaced rather
 * than read, on both sides.
 */
export const HOOK_MARKER_VERSION = 1;

export const HOOK_FILE = `${GROUND_CONTROL_DIR}/codex-hook.mjs`;
export const ACTIVITY_DIR = `${GROUND_CONTROL_DIR}/codex-activity`;

function under(home: string, suffix: string): string {
  return `${normalize(home).replace(/\/+$/, '')}/${suffix}`;
}

/**
 * The file the hook entries go in. Codex keeps hooks in a file of their own rather than in its settings, and
 * `CODEX_HOME` moves the whole directory — which is why this takes the environment rather than assuming `~/.codex`.
 */
export function codexHooksPathOf(home: string, env: NodeJS.ProcessEnv = {}): string {
  const configured = env['CODEX_HOME']?.trim();

  return configured ? `${normalize(configured).replace(/\/+$/, '')}/hooks.json` : under(home, '.codex/hooks.json');
}

/** Where Codex saves its threads, which moves with `CODEX_HOME` the same way its hooks do. */
export function codexHomeOf(home: string, env: NodeJS.ProcessEnv = {}): string {
  const configured = env['CODEX_HOME']?.trim();

  return configured ? normalize(configured).replace(/\/+$/, '') : under(home, '.codex');
}

export function hookPathOf(home: string): string {
  return under(home, HOOK_FILE);
}

export function activityDirOf(home: string): string {
  return under(home, ACTIVITY_DIR);
}

export function markerPathOf(home: string, sessionId: string): string {
  return `${activityDirOf(home)}/${sessionId}.json`;
}

/** The writer joins its own path from segments, so it needs no escaping and no separator of either platform. */
const ACTIVITY_SEGMENTS = ACTIVITY_DIR.split('/')
  .map((segment) => `'${segment}'`)
  .join(', ');

/**
 * How far ahead of a reader's clock a marker may sit and still be believed. The writer will not replace a newer
 * marker and `readActivity` will not read one further ahead than this, so the bounds are one number.
 */
export const FUTURE_TOLERANCE_MS = 60_000;

/** How long the pid walk may take. Under the 5 s the installed entry asks for, and the 3 s Codex clamps two events to. */
export const PID_WALK_TIMEOUT_MS = 2_500;

/** How far up the process tree Codex may be. Measured at two hops — a shell, then Codex (`docs/mechanics.md` M40). */
export const PID_WALK_HOPS = 3;

/**
 * The activity writer, shipped as a string so it has no packaging surface and vitest can spawn real `node` against
 * it. It transcribes the payload and resolves the one fact the payload lacks: the pid of the Codex process running
 * the session, which is what proves the session is still alive — Codex has no roster command, and a killed process
 * fires no `SessionEnd` (`docs/mechanics.md` M39, M40).
 */
export const HOOK_SOURCE = `// Ground Control Codex session activity writer. Records the hook event; the board decides the phase.
// Generated by the Ground Control extension. Edits are overwritten.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { homedir, platform } from 'node:os';
import { join } from 'node:path';

const DIR = join(homedir(), ${ACTIVITY_SEGMENTS});
const VERSION = ${HOOK_MARKER_VERSION};

// Only these two may create a marker. Every other event updates one, so a \`Stop\` still in flight when the
// synchronous \`SessionEnd\` removed the marker cannot put the session back on the board (\`docs/mechanics.md\` M40).
const CREATES = new Set(['SessionStart', 'UserPromptSubmit']);

// Codex runs a command hook through a shell, so its own process is this script's grandparent and no environment
// variable carries the pid. Walked only on an event that creates a marker, and copied forward by every later one.
function codexPid() {
  try {
    if (platform() === 'win32') {
      // \`Get-CimInstance\` rather than \`(Get-Process).Parent\`, which is PowerShell 7's and absent from the 5.1 on
      // every Windows: a walk that throws there would leave every session unprovable.
      const script = [
        '$id = ' + process.ppid,
        'for ($i = 0; $i -lt ${PID_WALK_HOPS} -and $id; $i++) {',
        '  $p = Get-CimInstance Win32_Process -Filter "ProcessId=$id"',
        '  if (-not $p) { break }',
        "  if ($p.Name.ToLower().Contains('codex')) { $p.ProcessId; break }",
        '  $id = $p.ParentProcessId',
        '}',
      ].join('\\n');
      const printed = execFileSync('powershell', ['-NoProfile', '-NonInteractive', '-Command', script], {
        encoding: 'utf8',
        timeout: ${PID_WALK_TIMEOUT_MS},
        windowsHide: true,
      });
      const found = Number.parseInt(printed.trim(), 10);

      return Number.isInteger(found) && found > 0 ? found : null;
    }

    let pid = process.ppid;

    for (let hop = 0; hop < ${PID_WALK_HOPS} && pid > 1; hop++) {
      const ps = (format) =>
        execFileSync('ps', ['-o', format, '-p', String(pid)], { encoding: 'utf8', timeout: ${PID_WALK_TIMEOUT_MS} }).trim();

      if (ps('comm=').toLowerCase().includes('codex')) {
        return pid;
      }

      pid = Number.parseInt(ps('ppid='), 10);
    }

    return null;
  } catch {
    return null;
  }
}

// A marker of another version is not ours to read: its fields may have been redefined. Absent to this writer, which
// then replaces it.
function readMarker(path) {
  try {
    const held = JSON.parse(readFileSync(path, 'utf8'));

    return held && held.v === VERSION ? held : null;
  } catch {
    return null;
  }
}

function exists(path) {
  try {
    readFileSync(path);

    return true;
  } catch (error) {
    return error.code !== 'ENOENT';
  }
}

try {
  const payload = JSON.parse(readFileSync(0, 'utf8'));
  const id = payload.session_id;
  const event = typeof payload.hook_event_name === 'string' ? payload.hook_event_name : null;

  // Also the traversal guard: a session id is the file name, and the payload is not ours.
  if (typeof id === 'string' && /^[A-Za-z0-9._-]+$/.test(id)) {
    const marker = DIR + '/' + id + '.json';

    if (event === 'SessionEnd') {
      for (let attempt = 0; ; attempt++) {
        try {
          rmSync(marker, { force: true });
          break;
        } catch (error) {
          if (attempt === 20) {
            throw error;
          }

          Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);
        }
      }
    } else {
      let prior = readMarker(marker);

      // A session the board has never seen begins at its start or its first prompt. Anything else with no marker is
      // an event arriving after the session ended, and putting a marker back would leave a card nothing ever clears.
      // A start with a marker already there is the same race the other way: the session's first prompt landed in the
      // same millisecond, and the start claims no phase — so it would cost the card its phase for the first turn.
      if (event === 'SessionStart' ? prior === null : prior !== null || CREATES.has(event)) {
        mkdirSync(DIR, { recursive: true });

        // The walk costs a process spawn, so it runs before the read-and-write below rather than inside it — a
        // second of walking between reading the marker and replacing it is a second of another event being lost —
        // and only on an event that may create one, so a tool call never pays for a walk that keeps failing.
        const walking = CREATES.has(event) && (prior === null || !Number.isInteger(prior.pid));
        const walked = walking ? codexPid() : null;

        if (walking) {
          prior = readMarker(marker);
        }

        const now = Date.now();
        const held = prior && prior.at;

        // Hooks run concurrently, so two race at a turn boundary and the slower one would otherwise land last with
        // the older observation. Bounded, because a marker further ahead than a reader will believe must stay
        // replaceable.
        if (typeof held === 'number' && held > now && held <= now + ${FUTURE_TOLERANCE_MS}) {
          process.exit(0);
        }

        const turnId = typeof payload.turn_id === 'string' ? payload.turn_id : null;

        // Codex names the turn on every event that belongs to one, so the stretch of work a running card counts is
        // bounded by evidence: a turn id the marker has not seen starts the count, and no turn ends it.
        let turnAt = prior && typeof prior.turnAt === 'number' ? prior.turnAt : null;

        if (turnId === null) {
          turnAt = null;
        } else if (!prior || prior.turnId !== turnId || turnAt === null) {
          turnAt = now;
        }

        // A start that walked for a second may find the session's first prompt already written, and the start
        // claims no phase — so it stands down rather than costing the card its phase for the whole first turn.
        if (event === 'SessionStart' && (prior !== null || exists(marker))) {
          process.exit(0);
        }

        const tmp = marker + '.' + process.pid + '.tmp';

        writeFileSync(
          tmp,
          JSON.stringify({
            v: VERSION,
            sessionId: id,
            event,
            at: now,
            turnAt,
            turnId,
            pid: prior && Number.isInteger(prior.pid) ? prior.pid : walked,
            startedAt: prior && typeof prior.startedAt === 'number' ? prior.startedAt : now,
            cwd: typeof payload.cwd === 'string' ? payload.cwd : null,
            transcriptPath: typeof payload.transcript_path === 'string' ? payload.transcript_path : null,
            model: typeof payload.model === 'string' ? payload.model : null,
            permissionMode: typeof payload.permission_mode === 'string' ? payload.permission_mode : null,
            source: typeof payload.source === 'string' ? payload.source : null,
            toolName: typeof payload.tool_name === 'string' ? payload.tool_name : null,
            reason: typeof payload.reason === 'string' ? payload.reason : null,
          }),
        );

        // A reader polls this directory, so a partial file must never be visible under the marker's own name. The
        // rename is retried because Windows refuses one over a file a concurrent writer still holds open.
        for (let attempt = 0; ; attempt++) {
          try {
            renameSync(tmp, marker);
            break;
          } catch (error) {
            if (attempt === 20) {
              rmSync(tmp, { force: true });
              throw error;
            }

            // The writer is synchronous by design — a hook's decision is its exit code — so the wait is too.
            Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);
          }
        }
      }
    }
  }
} catch {
  // Deliberately silent. A hook's exit code and stdout are a decision on PermissionRequest and injected context on
  // UserPromptSubmit, so a broken writer must not be able to veto the work.
}

process.exit(0);
`;
