import { GROUND_CONTROL_DIR, normalize } from '@ground-control/core';

/**
 * Increment for changed field semantics, not compatible additions. Shared-home readers reject incompatible
 * versions; writers replace them.
 */
export const HOOK_MARKER_VERSION = 1;

export const HOOK_FILE = `${GROUND_CONTROL_DIR}/codex-hook.mjs`;
export const ACTIVITY_DIR = `${GROUND_CONTROL_DIR}/codex-activity`;

function under(home: string, suffix: string): string {
  return `${rootPath(home).replace(/\/+$/, '')}/${suffix}`;
}

function rootPath(value: string): string {
  return /^[a-z]:[\\/]|^\\\\/i.test(value) ? normalize(value) : value;
}

/** Resolve hooks.json under CODEX_HOME or ~/.codex; Codex stores hooks separately from settings. */
export function codexHooksPathOf(home: string, env: NodeJS.ProcessEnv = {}): string {
  return under(codexHomeOf(home, env), 'hooks.json');
}

/** Resolve Codex storage, respecting CODEX_HOME. */
export function codexHomeOf(home: string, env: NodeJS.ProcessEnv = {}): string {
  const configured = env['CODEX_HOME'];
  if (configured === undefined) return under(home, '.codex');
  const root = rootPath(configured);
  return root === '/' || /^[a-z]:\/$/i.test(root) ? root : root.replace(/\/+$/, '');
}

export function hookPathOf(home: string): string {
  return under(home, HOOK_FILE);
}

export function activityDirOf(home: string): string {
  return under(home, ACTIVITY_DIR);
}

export function markerPathOf(home: string, sessionId: string): string {
  return `${activityDirOf(home)}/${sessionId}.json`;
}

/** Generate path segments for platform-independent joining in the writer. */
const ACTIVITY_SEGMENTS = ACTIVITY_DIR.split('/')
  .map((segment) => `'${segment}'`)
  .join(', ');

/**
 * Shared clock tolerance for readers and writers. Reject far-future markers but allow replacing them after a
 * backward clock change.
 */
export const FUTURE_TOLERANCE_MS = 60_000;

/** Process ancestry timeout, below the installed five-second limit and Codex's three-second event limit. */
export const PID_WALK_TIMEOUT_MS = 2_500;

/** How far up the process tree Codex may be. Measured at two hops — a shell, then Codex (`docs/mechanics.md` M40). */
export const PID_WALK_HOPS = 3;

/**
 * Bundle a standalone writer for installation and subprocess tests. Record hook fields and resolve the Codex
 * PID, which is absent from payloads and required for liveness checks (M39, M40).
 */
export const HOOK_SOURCE = `// Ground Control Codex session activity writer. Records the hook event; the board decides the phase.
// Generated by the Ground Control extension. Edits are overwritten.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { homedir, platform } from 'node:os';
import { join } from 'node:path';

const DIR = join(homedir(), ${ACTIVITY_SEGMENTS});
const VERSION = ${HOOK_MARKER_VERSION};

// Only SessionStart and UserPromptSubmit create markers. Later asynchronous events must not recreate a marker
// removed by SessionEnd (M40).
const CREATES = new Set(['SessionStart', 'UserPromptSubmit']);

// Resolve the Codex ancestor PID through the hook shell only when creating markers; later events preserve it.
function codexPid() {
  try {
    if (platform() === 'win32') {
      // Use Get-CimInstance because Windows PowerShell 5.1 lacks Get-Process.Parent.
      const script = [
        '$id = ' + process.ppid,
        'for ($i = 0; $i -lt ${PID_WALK_HOPS} -and $id; $i++) {',
        '  $p = Get-CimInstance Win32_Process -Filter "ProcessId=$id"',
        '  if (-not $p) { break }',
        "  if ($p.Name.ToLower().Contains('codex')) { $p.ProcessId; break }",
        '  $id = $p.ParentProcessId',
        '}',
      ].join('\\n');
      const printed = execFileSync('powershell', ['-NoProfile', '-NonInteractive', '-Command', script], {
        encoding: 'utf8',
        timeout: ${PID_WALK_TIMEOUT_MS},
        windowsHide: true,
      });
      const found = Number.parseInt(printed.trim(), 10);

      return Number.isInteger(found) && found > 0 ? found : null;
    }

    let pid = process.ppid;

    for (let hop = 0; hop < ${PID_WALK_HOPS} && pid > 1; hop++) {
      const ps = (format) =>
        execFileSync('ps', ['-o', format, '-p', String(pid)], { encoding: 'utf8', timeout: ${PID_WALK_TIMEOUT_MS} }).trim();

      if (ps('comm=').toLowerCase().includes('codex')) {
        return pid;
      }

      pid = Number.parseInt(ps('ppid='), 10);
    }

    return null;
  } catch {
    return null;
  }
}

// Treat incompatible marker versions as absent so the writer replaces them.
function readMarker(path) {
  try {
    const held = JSON.parse(readFileSync(path, 'utf8'));

    return held && held.v === VERSION ? held : null;
  } catch {
    return null;
  }
}

function exists(path) {
  try {
    readFileSync(path);

    return true;
  } catch (error) {
    return error.code !== 'ENOENT';
  }
}

try {
  const payload = JSON.parse(readFileSync(0, 'utf8'));
  const id = payload.session_id;
  const event = typeof payload.hook_event_name === 'string' ? payload.hook_event_name : null;

  // Validate the external session ID before using it as a filename.
  if (typeof id === 'string' && /^[A-Za-z0-9._-]+$/.test(id)) {
    const marker = DIR + '/' + id + '.json';

    if (event === 'SessionEnd') {
      for (let attempt = 0; ; attempt++) {
        try {
          rmSync(marker, { force: true });
          break;
        } catch (error) {
          if (attempt === 20) {
            throw error;
          }

          Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);
        }
      }
    } else {
      let prior = readMarker(marker);

      // Ignore late events without markers after SessionEnd. Ignore SessionStart when a prompt has already
      // created a marker, preserving the first turn phase.
      if (event === 'SessionStart' ? prior === null : prior !== null || CREATES.has(event)) {
        mkdirSync(DIR, { recursive: true });

        // Resolve ancestry before rereading the marker to reduce concurrent-update loss. Retry missing PIDs
        // only on marker-creating events.
        const walking = CREATES.has(event) && (prior === null || !Number.isInteger(prior.pid));
        const walked = walking ? codexPid() : null;

        if (walking) {
          prior = readMarker(marker);
        }

        const now = Date.now();
        const held = prior && prior.at;

        // Keep newer concurrent events within the clock tolerance; allow replacing far-future markers.
        if (typeof held === 'number' && held > now && held <= now + ${FUTURE_TOLERANCE_MS}) {
          process.exit(0);
        }

        const turnId = typeof payload.turn_id === 'string' ? payload.turn_id : null;

        // Start timing when turn_id changes; clear turn start for events outside a turn.
        let turnAt = prior && typeof prior.turnAt === 'number' ? prior.turnAt : null;

        if (turnId === null) {
          turnAt = null;
        } else if (!prior || prior.turnId !== turnId || turnAt === null) {
          turnAt = now;
        }

        // A prompt can create the marker during ancestry lookup. Do not overwrite its running phase with
        // SessionStart.
        if (event === 'SessionStart' && (prior !== null || exists(marker))) {
          process.exit(0);
        }

        const tmp = marker + '.' + process.pid + '.tmp';

        writeFileSync(
          tmp,
          JSON.stringify({
            v: VERSION,
            sessionId: id,
            event,
            at: now,
            turnAt,
            turnId,
            pid: prior && Number.isInteger(prior.pid) ? prior.pid : walked,
            startedAt: prior && typeof prior.startedAt === 'number' ? prior.startedAt : now,
            cwd: typeof payload.cwd === 'string' ? payload.cwd : null,
            transcriptPath: typeof payload.transcript_path === 'string' ? payload.transcript_path : null,
            profileRoot: process.env.CODEX_HOME || join(homedir(), '.codex'),
            model: typeof payload.model === 'string' ? payload.model : null,
            permissionMode: typeof payload.permission_mode === 'string' ? payload.permission_mode : null,
            source: typeof payload.source === 'string' ? payload.source : null,
            toolName: typeof payload.tool_name === 'string' ? payload.tool_name : null,
            reason: typeof payload.reason === 'string' ? payload.reason : null,
          }),
        );

        // Rename atomically to exclude partial reads. Retry Windows file-lock failures from concurrent writers.
        for (let attempt = 0; ; attempt++) {
          try {
            renameSync(tmp, marker);
            break;
          } catch (error) {
            if (attempt === 20) {
              rmSync(tmp, { force: true });
              throw error;
            }

            // Keep retries synchronous because the hook result depends on process exit.
            Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);
          }
        }
      }
    }
  }
} catch {
  // Keep stdout empty and exit successfully on writer errors; hook output can affect permissions or inject
  // prompt context.
}

process.exit(0);
`;
