import { createHash } from 'node:crypto';
import { constants, copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync, statSync, utimesSync } from 'node:fs';
import { hookPathOf as claudeHookPathOf } from '@ground-control/agent-claude';
import { hookPathOf as codexHookPathOf } from '@ground-control/agent-codex';
import {
  NATIVE_HOST_NAME,
  STATE_POINTER_FILE,
  basename,
  bootstrapDirOf,
  dirKey,
  formatStatePointer,
  normalize,
  parent,
  resolveStateDir,
  stateDirSchema,
  statePointerPathOf,
} from '@ground-control/core';
import { makeActionStore } from './actionStore.js';
import { findHub, stopHub } from './discover.js';
import { read, releaseLock, takeLock, writeDurable } from './fs.js';
import { relocateLockPathOf } from './paths.js';

/** Files that stay in the bootstrap directory because external programs are registered to launch or read them there. */
export function launchArtifacts(home: string): ReadonlySet<string> {
  return new Set([
    STATE_POINTER_FILE,
    'hub.js',
    basename(relocateLockPathOf(home)),
    basename(claudeHookPathOf(home)),
    basename(codexHookPathOf(home)),
    'ground-control-bridge.cmd',
    'ground-control-bridge.sh',
    `${NATIVE_HOST_NAME}.json`,
  ]);
}

/** Regenerated by the next hub or writer; never copied, and allowed at a destination. */
function isTransient(name: string): boolean {
  return name === 'hub.json' || name === 'hub-exit.json' || name === 'install.lock' || name.endsWith('.tmp');
}

/** Interpret the `groundControl.stateDirectory` setting; empty selects the bootstrap directory. */
export function relocationTarget(home: string, setting: string): { stateDir: string } | { refused: string } {
  if (setting.trim() === '') {
    return { stateDir: bootstrapDirOf(home) };
  }

  const parsed = stateDirSchema.safeParse(setting);

  return parsed.success
    ? { stateDir: parsed.data }
    : { refused: `groundControl.stateDirectory must be an absolute path without surrounding whitespace: "${setting}".` };
}

export interface RelocationFs {
  /** Entry names, or null when the path is not a directory. */
  list(dir: string): string[] | null;
  isFile(path: string): boolean;
  /** The path with links and junctions resolved, or null when it does not exist. */
  realPath(path: string): string | null;
}

export const realRelocationFs: RelocationFs = {
  list(dir) {
    try {
      return readdirSync(dir);
    } catch {
      return null;
    }
  },
  isFile(path) {
    try {
      return statSync(path).isFile();
    } catch {
      return false;
    }
  },
  realPath(path) {
    try {
      return normalize(realpathSync.native(path));
    } catch {
      return null;
    }
  },
};

/** The resolved path of the nearest existing ancestor, with the missing tail appended, so aliases cannot hide nesting. */
function resolved(path: string, fs: RelocationFs): string {
  const missing: string[] = [];

  for (let held: string | null = path; held !== null; held = parent(held)) {
    const real = fs.realPath(held);

    if (real !== null) {
      return [real, ...missing].join('/');
    }

    missing.unshift(basename(held));
  }

  return path;
}

/** Why a destination cannot receive the state, or null when the move may proceed. Equal directories are the caller's no-op. */
export function relocationRefusal(home: string, from: string, to: string, fs: RelocationFs = realRelocationFs): string | null {
  const fromKey = `${dirKey(resolved(from, fs))}/`;
  const toKey = `${dirKey(resolved(to, fs))}/`;

  if (fromKey === toKey || toKey.startsWith(fromKey) || fromKey.startsWith(toKey)) {
    return `The state directory ${to} cannot be inside the current one, or contain it.`;
  }

  if (fs.isFile(to)) {
    return `${to} is a file, not a directory.`;
  }

  const artifacts = launchArtifacts(home);
  const entries = fs.list(to) ?? [];
  const blocking = entries.filter((name) => !artifacts.has(name) && !isTransient(name));

  if (blocking.length > 0) {
    return `${to} already contains ${blocking.length === 1 ? 'a file' : `${blocking.length} files`} (${blocking.slice(0, 3).join(', ')}). Choose an empty directory.`;
  }

  return null;
}

export interface RelocationDeps {
  home: string;
  now(): number;
  sleep(ms: number): Promise<void>;
  /** Request authenticated shutdown of the hub recorded in a state directory. */
  stopHub(stateDir: string): Promise<boolean>;
  /** Whether anything still answers on the recorded hub port. */
  hubIsLive(stateDir: string): Promise<boolean>;
}

export type Relocation =
  | { stateDir: string; moved: number; leftover: string[] }
  | { refused: string }
  | { failed: string }
  | { busy: true };

/** How long a stopped hub may take to release its record and log. */
const STOP_TIMEOUT_MS = 5000;
const STOP_POLL_MS = 100;

function writePointer(home: string, stateDir: string, migrationTo: string | null, now: number): void {
  const path = statePointerPathOf(home);

  if (migrationTo === null && dirKey(stateDir) === dirKey(bootstrapDirOf(home))) {
    rmSync(path, { force: true });

    return;
  }

  mkdirSync(bootstrapDirOf(home), { recursive: true });
  writeDurable(
    path,
    formatStatePointer({
      stateDir,
      ...(migrationTo === null ? {} : { migration: { to: migrationTo, startedAt: new Date(now).toISOString() } }),
    }),
  );
}

function hashOf(path: string): string {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

/** Copy one entry recursively without overwriting, then verify every file's bytes. */
function copyVerified(source: string, target: string, onProgress: () => void): void {
  onProgress();

  if (statSync(source).isDirectory()) {
    mkdirSync(target, { recursive: true });

    for (const name of readdirSync(source)) {
      copyVerified(`${source}/${name}`, `${target}/${name}`, onProgress);
    }

    return;
  }

  copyFileSync(source, target, constants.COPYFILE_EXCL);

  if (hashOf(source) !== hashOf(target)) {
    throw new Error(`${target} does not match ${source} after copying.`);
  }
}

/** Card actions dispatched from the current directory were told to report there; moving under them would lose their results. */
function runningActions(stateDir: string): number {
  return Object.values(makeActionStore(stateDir).read().runs).filter((run) => run.outcome === 'running').length;
}

/**
 * Move the state directory. The pointer records the migration first so no hub starts against either directory,
 * the hub is stopped, entries are copied and verified, the pointer is committed, and only then are sources
 * removed. Any failure before commit restores the previous pointer and removes the copies this move created.
 */
export async function relocateState(to: string, deps: RelocationDeps): Promise<Relocation> {
  const { home } = deps;
  const current = resolveStateDir(home, undefined, deps.now());
  const from = current.stateDir;

  if (current.problem !== null) {
    return { failed: `${current.problem} Fix or delete it in ${bootstrapDirOf(home)} before moving the state.` };
  }

  if (dirKey(from) === dirKey(to)) {
    return { stateDir: from, moved: 0, leftover: [] };
  }

  const refusal = relocationRefusal(home, from, to);

  if (refusal !== null) {
    return { refused: refusal };
  }

  if (realRelocationFs.list(from) === null) {
    return { failed: `The current state directory ${from} cannot be read, so its state cannot be moved.` };
  }

  const running = runningActions(from);

  if (running > 0) {
    return { refused: `${running === 1 ? 'A card action is' : `${running} card actions are`} still running from ${from}. Wait for or stop them, then try again.` };
  }

  const lock = relocateLockPathOf(home);

  mkdirSync(bootstrapDirOf(home), { recursive: true });

  if (!takeLock(lock, deps.now())) {
    return { busy: true };
  }

  const previous = read(statePointerPathOf(home));
  const restore = (): void => {
    if (previous === null) {
      rmSync(statePointerPathOf(home), { force: true });
    } else {
      writeDurable(statePointerPathOf(home), previous);
    }
  };
  /** Only entries this move created are removed on rollback; a collision belongs to someone else. */
  const copied: string[] = [];
  const createdTarget = !existsSync(to);
  const undoCopies = (): void => {
    for (const name of copied) {
      rmSync(`${to}/${name}`, { recursive: true, force: true });
    }

    if (createdTarget) {
      rmSync(to, { recursive: true, force: true });
    }
  };
  // Renew the lock while copying so a long copy is not mistaken for an abandoned move.
  const renew = (): void => {
    const at = new Date(deps.now());

    utimesSync(lock, at, at);
  };

  try {
    writePointer(home, from, to, deps.now());

    await deps.stopHub(from);

    for (const until = deps.now() + STOP_TIMEOUT_MS; await deps.hubIsLive(from); ) {
      if (deps.now() >= until) {
        restore();

        return { failed: `The hub serving ${from} did not stop. Close other Ground Control windows and try again.` };
      }

      await deps.sleep(STOP_POLL_MS);
    }

    const artifacts = launchArtifacts(home);
    const listed = realRelocationFs.list(from);

    if (listed === null) {
      restore();

      return { failed: `The current state directory ${from} cannot be read, so its state cannot be moved.` };
    }

    const names = listed.filter((name) => !artifacts.has(name) && !isTransient(name));

    try {
      mkdirSync(to, { recursive: true });

      for (const name of names) {
        if (existsSync(`${to}/${name}`)) {
          throw new Error(`${to}/${name} appeared at the destination.`);
        }

        copied.push(name);
        copyVerified(`${from}/${name}`, `${to}/${name}`, renew);
      }

      writePointer(home, to, null, deps.now());
    } catch (error) {
      undoCopies();
      restore();

      return { failed: `Could not move Ground Control state to ${to}: ${(error as Error).message} The state remains in ${from}.` };
    }

    const leftover: string[] = [];

    for (const name of names) {
      try {
        rmSync(`${from}/${name}`, { recursive: true, force: true });
      } catch {
        leftover.push(`${from}/${name}`);
      }
    }

    return { stateDir: to, moved: names.length, leftover };
  } finally {
    releaseLock(lock);
  }
}

/**
 * Clear a migration marker nobody is performing, so hubs can start again. Copies at the destination are left for
 * the developer; a later move there is refused until they are removed.
 */
export function recoverRelocation(home: string, now: number = Date.now()): string | null {
  const resolved = resolveStateDir(home, undefined, now);
  const to = resolved.migratingTo ?? resolved.interruptedTo;

  if (to === null) {
    return null;
  }

  const lock = relocateLockPathOf(home);

  if (!takeLock(lock, now)) {
    return null;
  }

  try {
    writePointer(home, resolved.stateDir, null, now);
  } finally {
    releaseLock(lock);
  }

  return `A move of Ground Control state to ${to} did not finish. State remains in ${resolved.stateDir}; remove any files copied to ${to} before choosing it again.`;
}

export function realRelocationDeps(home: string): RelocationDeps {
  return {
    home,
    now: () => Date.now(),
    sleep: (ms) => new Promise((done) => setTimeout(done, ms)),
    stopHub: (stateDir) => stopHub(stateDir),
    hubIsLive: async (stateDir) => {
      const found = await findHub(stateDir);

      return 'hub' in found || (found.miss.why !== 'no-record' && found.miss.why !== 'unreachable');
    },
  };
}
