import { GROUND_CONTROL_DIR, normalize } from '@ground-control/core';

/**
 * Increment for changed field semantics, not compatible additions. Readers reject incompatible versions;
 * installation updates the writer when its contents differ.
 */
export const HOOK_MARKER_VERSION = 1;

export const HOOK_FILE = `${GROUND_CONTROL_DIR}/hook.mjs`;
export const ACTIVITY_DIR = `${GROUND_CONTROL_DIR}/activity`;

function under(home: string, suffix: string): string {
  return `${normalize(home).replace(/\/+$/, '')}/${suffix}`;
}

/** Shared Claude user settings containing hook entries. */
export function claudeSettingsPathOf(home: string): string {
  return under(home, '.claude/settings.json');
}

export function hookPathOf(home: string): string {
  return under(home, HOOK_FILE);
}

export function activityDirOf(home: string): string {
  return under(home, ACTIVITY_DIR);
}

export function markerPathOf(home: string, sessionId: string): string {
  return `${activityDirOf(home)}/${sessionId}.json`;
}

/** Generate path segments for platform-independent joining in the writer. */
const ACTIVITY_SEGMENTS = ACTIVITY_DIR.split('/')
  .map((segment) => `'${segment}'`)
  .join(', ');

/**
 * Shared clock tolerance for readers and writers. Reject far-future markers but allow replacing them after a
 * backward clock change.
 */
export const FUTURE_TOLERANCE_MS = 60_000;

/**
 * Bundle the standalone writer as a string for installation and subprocess tests. Record payload fields; keep
 * phase mapping in the extension.
 */
export const HOOK_SOURCE = `// Ground Control session activity writer. Records the hook event; the board decides the phase.
// Generated by the Ground Control extension. Edits are overwritten.
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const DIR = join(homedir(), ${ACTIVITY_SEGMENTS});

try {
  const payload = JSON.parse(readFileSync(0, 'utf8'));
  const id = payload.session_id;

  // Ignore subagent hooks carrying the parent session ID; their tool events could overwrite a parent waiting
  // for input (R6).
  const isParentSession = typeof payload.agent_id !== 'string';

  // Validate the external session ID before using it as a filename.
  if (isParentSession && typeof id === 'string' && /^[A-Za-z0-9._-]+$/.test(id)) {
    const marker = DIR + '/' + id + '.json';

    if (payload.hook_event_name === 'SessionEnd') {
      rmSync(marker, { force: true });
    } else {
      mkdirSync(DIR, { recursive: true });

      const now = Date.now();
      let prior = null;

      try {
        prior = JSON.parse(readFileSync(marker, 'utf8'));
      } catch {}

      const held = prior && prior.at;

      // Keep newer concurrent events within the clock tolerance; allow replacing far-future markers.
      if (typeof held === 'number' && held > now && held <= now + ${FUTURE_TOLERANCE_MS}) {
        process.exit(0);
      }

      const event = typeof payload.hook_event_name === 'string' ? payload.hook_event_name : null;
      const backgroundTasks = Array.isArray(payload.background_tasks) ? payload.background_tasks.length : 0;
      let turnAt = prior && typeof prior.turnAt === 'number' ? prior.turnAt : null;

      // Preserve turn start across tool events so the running duration does not reset after each batch.
      if (event === 'UserPromptSubmit') {
        turnAt = now;
      } else if (
        // Clear turn start after completion or a new session start.
        (event === 'Stop' && backgroundTasks === 0) ||
        (event === 'Notification' && payload.notification_type === 'agent_completed') ||
        (event === 'SessionStart' && payload.source !== 'compact')
      ) {
        turnAt = null;
      } else if (turnAt === null) {
        // Start timing at the first resumed event when no prompt was recorded, including scheduled work and
        // newly installed hooks.
        turnAt = now;
      }

      const tmp = marker + '.' + process.pid + '.tmp';

      writeFileSync(
        tmp,
        JSON.stringify({
          v: ${HOOK_MARKER_VERSION},
          sessionId: id,
          event,
          at: now,
          turnAt,
          cwd: typeof payload.cwd === 'string' ? payload.cwd : null,
          notificationType: typeof payload.notification_type === 'string' ? payload.notification_type : null,
          source: typeof payload.source === 'string' ? payload.source : null,
          toolName: typeof payload.tool_name === 'string' ? payload.tool_name : null,
          reason: typeof payload.reason === 'string' ? payload.reason : null,
          backgroundTasks,
        }),
      );

      // Rename atomically so readers never observe partial marker files.
      renameSync(tmp, marker);
    }
  }
} catch {
  // Do not change hook decisions: exit 2 can deny PermissionRequest or block UserPromptSubmit, and stdout can
  // inject context. Writer failures must leave work unaffected.
}

process.exit(0);
`;
