import { GROUND_CONTROL_DIR, normalize } from '@ground-control/core';

/**
 * Bumped when a field's meaning changes, not when one is added: two extension versions share one `~/.claude`, and an added field is absent to the
 * older reader and defaulted by the newer one. The extension rewrites the writer whenever its bytes differ.
 */
export const HOOK_MARKER_VERSION = 1;

export const HOOK_FILE = `${GROUND_CONTROL_DIR}/hook.mjs`;
export const ACTIVITY_DIR = `${GROUND_CONTROL_DIR}/activity`;

function under(home: string, suffix: string): string {
  return `${normalize(home).replace(/\/+$/, '')}/${suffix}`;
}

/** The file the hook entries go in: the developer's own user settings, shared by every session on the machine. */
export function claudeSettingsPathOf(home: string): string {
  return under(home, '.claude/settings.json');
}

export function hookPathOf(home: string): string {
  return under(home, HOOK_FILE);
}

export function activityDirOf(home: string): string {
  return under(home, ACTIVITY_DIR);
}

export function markerPathOf(home: string, sessionId: string): string {
  return `${activityDirOf(home)}/${sessionId}.json`;
}

/** The writer joins its own path from segments, so it needs no escaping and no separator of either platform. */
const ACTIVITY_SEGMENTS = ACTIVITY_DIR.split('/')
  .map((segment) => `'${segment}'`)
  .join(', ');

/**
 * How far ahead of a reader's clock a marker may sit and still be believed. The writer will not replace a newer marker and `readActivity` will
 * not read one further ahead than this, so the bounds are one number — otherwise a backward clock step wedges a marker nothing can touch.
 */
export const FUTURE_TOLERANCE_MS = 60_000;

/**
 * The activity writer, shipped as a string so it has no packaging surface and vitest can spawn real `node` against it. It transcribes the payload
 * and decides nothing — the phase is `phaseOf`'s, so a mapping bug ships as an extension update, not a rewrite of a file in the developer's home.
 */
export const HOOK_SOURCE = `// Ground Control session activity writer. Records the hook event; the board decides the phase.
// Generated by the Ground Control extension. Edits are overwritten.
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const DIR = join(homedir(), ${ACTIVITY_SEGMENTS});

try {
  const payload = JSON.parse(readFileSync(0, 'utf8'));
  const id = payload.session_id;

  // A subagent's hooks carry the parent's session id, so its tool batches would land on the parent as \`running\` -
  // clearing a \`waiting\` on a session actually parked on a prompt, which is the one case R6 exists for.
  const mine = typeof payload.agent_id !== 'string';

  // Also the traversal guard: a session id is the file name, and the payload is not ours.
  if (mine && typeof id === 'string' && /^[A-Za-z0-9._-]+$/.test(id)) {
    const marker = DIR + '/' + id + '.json';

    if (payload.hook_event_name === 'SessionEnd') {
      rmSync(marker, { force: true });
    } else {
      mkdirSync(DIR, { recursive: true });

      const now = Date.now();
      let prior = null;

      try {
        prior = JSON.parse(readFileSync(marker, 'utf8'));
      } catch {}

      const held = prior && prior.at;

      // Hooks run async, so two race at a turn boundary and the slower one would otherwise land last with the older
      // observation. Bounded, because a marker further ahead than a reader will believe must stay replaceable.
      if (typeof held === 'number' && held > now && held <= now + ${FUTURE_TOLERANCE_MS}) {
        process.exit(0);
      }

      const event = typeof payload.hook_event_name === 'string' ? payload.hook_event_name : null;
      const backgroundTasks = Array.isArray(payload.background_tasks) ? payload.background_tasks.length : 0;
      let turnAt = prior && typeof prior.turnAt === 'number' ? prior.turnAt : null;

      // When the stretch of work in flight began - the writer's one piece of state, because a running card counts the stretch and an event-time
      // anchor holds that count at zero on every tool batch. A prompt starts one.
      if (event === 'UserPromptSubmit') {
        turnAt = now;
      } else if (
        // The session saying it has finished ends the stretch, and so does a new run. Nothing after this point belongs to the work before it.
        (event === 'Stop' && backgroundTasks === 0) ||
        (event === 'Notification' && payload.notification_type === 'agent_completed') ||
        (event === 'SessionStart' && payload.source !== 'compact')
      ) {
        turnAt = null;
      } else if (turnAt === null) {
        // Work resuming with no prompt behind it: a background wake, a cron, a session already running when the hooks were installed. The
        // stretch starts here, because the alternative is a card that reports the age of its last heartbeat and reads zero all the way through.
        turnAt = now;
      }

      const tmp = marker + '.' + process.pid + '.tmp';

      writeFileSync(
        tmp,
        JSON.stringify({
          v: ${HOOK_MARKER_VERSION},
          sessionId: id,
          event,
          at: now,
          turnAt,
          cwd: typeof payload.cwd === 'string' ? payload.cwd : null,
          notificationType: typeof payload.notification_type === 'string' ? payload.notification_type : null,
          source: typeof payload.source === 'string' ? payload.source : null,
          toolName: typeof payload.tool_name === 'string' ? payload.tool_name : null,
          reason: typeof payload.reason === 'string' ? payload.reason : null,
          backgroundTasks,
        }),
      );

      // A reader polls this directory, so a partial file must never be visible under the marker's own name.
      renameSync(tmp, marker);
    }
  }
} catch {
  // Deliberately silent. Exit 2 is *deny* on PermissionRequest and *block* on UserPromptSubmit, and stdout is a
  // decision on the one and injected context on the other, so a broken writer must not be able to veto the work.
}

process.exit(0);
`;
