export { VSCODE_HOST_ID, makeVscodeHost } from './adapter.js';
export type { VscodeConfig, VscodeHost, VscodeRoute } from './adapter.js';
export { changesPlan, noRepository, repositoryRefusal } from './changes.js';
export type { ChangeKind, ChangedPath, ChangesPlan, ChangesRequest, DiffRow, DiffSide } from './changes.js';
export { stagedUpdate, stagedUpdateRefusal } from './install.js';
export type { StagedUpdate } from './install.js';
export { PLACEMENTS, claudeDirOf } from './placements.js';
export { DEFAULT_URI_SCHEME, attachFromUri, handOverUri, handedOver, handoverToken, sessionFromUri, uriSchemeOf } from './openUri.js';
export type { AgentPlacement, CommandArg, CommandCall } from './placements.js';
export { SETTLING_MS, VSCODE_ROUTES, openableSessions, planCheckout, planOpen, planStart, resumeRefusal, startableAgents, strayFrom, verifyOpen } from './open.js';
export type { OpenSettings } from './open.js';
export { projectDirName, repositoryWindowFor, worktreePointer } from './worktree.js';
export type { WorktreePointer } from './worktree.js';
export { ideWindowsFrom, listeningFrom, liveRootsOf, liveWindows, processesFrom, windowForProcess } from './ide.js';
export type { IdeLock, IdeWindow, ListeningPort, ProcessEntry } from './ide.js';
export { rootFrom, sidebarSession, surfacesFrom, tabSessions } from './surface.js';
export type { WindowStore } from './surface.js';
export { primeWindows, readWindows } from './windows.js';
export type { Windows } from './windows.js';
export { defaultUserDir, readWindowStores } from './stores.js';
